### ISSUE TITLE
How to get the raw predicted results

### ISSUE THREAD

**Issue by smallhelloworld** [Hanjun-Dai/graphnn#10]
I run the graph_classification example program and can get the results 
on accuracy and loss. Is it possible to directly get the predicted result?
The probabilities or the labels of the results. I tried to push 
the output into targets by adding 
targets.push_back(output);
at https://github.com/Hanjun-Dai/graphnn/blob/master/examples/graph_classification/src/kernel_mean_field.cpp#L61.

When retrieve the results, use 
dynamic_cast<TensorTemplate<mode, DENSE, Dtype>*>(t.get())->Serialize(outfile);
at line https://github.com/Hanjun-Dai/graphnn/blob/master/examples/graph_classification/include/nn_common.h#L167. 

Also I did some other little changes to make sure the first two elements are scalars and the newly-added element is tensor.

But this does not work well. It can create the outfile. But it is empty inside the file. Is there any suggestions on this? I plan to get the outputs and compute the AUC scores for the classification task.

**Comment by Hanjun-Dai** [comment]
Hi there,

After obtaining the variable 't', you can access its value by:

`auto& mat = t->value;`

And depends on your context, you would either get a tensor object on CPU or GPU. 
If you want to access the elements of that tensor directly, you can use the pointer 

`mat.data->ptr`  where it gets a row-major storage of the tensor object. 

Please see my latest commit. I've made an example in the mnist experiment. 

https://github.com/Hanjun-Dai/graphnn/commit/6944189702e785b39f43b973364b7e1615a7a27a
