### ISSUE TITLE
Which version of libfmt is being used?

### ISSUE THREAD

**Issue by cs-sun** [Hanjun-Dai/graphnn#12]
I have tried v4.0.0 and v3.0.0, and both of them cant run properly on example/mnist.

when compiling graphnn with libfmt v3.0.0 got warning:
```bash
include/fmt/format.h(2591): warning: statement is unreachable
```

and while running mnist example later got error:

```bash
➜  mnist ✗ make -j
g++ -Wall -O3 -std=c++11 -DUSE_GPU -I/usr/local/cuda/include -I/opt/intel/mkl/include -I../../include -Iinclude -o build/mnist mnist.cpp ../../build/lib/libgnn.a -L../../build/lib -lgnn -lm -L/usr/local/cuda/lib64 -lcudart -lcublas -lcurand -lcusparse -lmkl_rt -lfmt
/usr/bin/ld: cannot find -lfmt
collect2: error: ld returned 1 exit status
Makefile:21: recipe for target 'build/mnist' failed
make: *** [build/mnist] Error 1

```

**Comment by Hanjun-Dai** [comment]
I'm using v4.0.0. 

It seems that you haven't installed the libfmt properly. 
The message `cannot find -lfmt` tells that the libfmt library is not in your system path.

**Comment by ariewahyu** [comment]
I got the same problem

**Comment by Hanjun-Dai** [comment]
after cloning the libfmt, do the following:
`mkdir build`
`cd build`
`make -j`
`sudo make install`

you can also install to your local dir when needed.

But I'll try to remove this dependency shortly.

**Comment by ariewahyu** [comment]
I can run the code correctly.

**Comment by Hanjun-Dai** [comment]
I've included the core code of libfmt into this project. Now the graphnn library is self-contained, and no separate dependency of libfmt is needed.
