### ISSUE TITLE
Cannot found mkl.h

### ISSUE THREAD

**Issue by ariewahyu** [Hanjun-Dai/graphnn#14]
I tried to run the make, but it gives the error of cannot found mkl.h
Is it missing? Or should we create it?

Here is the error I got 

`g++ -Wall -O3 -std=c++11 -I/usr/local/cuda/include -I/home/abcde/anaconda2/lib/include -Iinclude -fPIC -DUSE_GPU -MMD -c -o build/objs/cxx/tensor/cpu_dense_tensor.o src/tensor/cpu_dense_tensor.cpp
In file included from src/tensor/cpu_dense_tensor.cpp:5:0:
include/tensor/mkl_helper.h:4:17: fatal error: mkl.h: No such file or directory
compilation terminated.
Makefile:53: recipe for target 'build/objs/cxx/tensor/cpu_dense_tensor.o' failed
make: *** [build/objs/cxx/tensor/cpu_dense_tensor.o] Error 1
`

**Comment by Hanjun-Dai** [comment]
Hi, you should specify the MKL_ROOT.

If the intel mkl is installed and you are in ubuntu, then by default it is located under /opt/intel/mkl

**Comment by ariewahyu** [comment]
Ok thanks
