### ISSUE TITLE
Do not find the 'modify' command

### ISSUE THREAD

**Issue by FFrankyy** [Hanjun-Dai/graphnn#15]
I have problems in Build Static Library section, 
modify configurations in make_common file
make -j8
these two commands do not work: do not find the modify command, what's the problem?

**Comment by Hanjun-Dai** [comment]
Hi there, could you provide more details of your problem?

You can paste your modified make_common file, and the relevant error log, your os detail (mac, ubuntu), etc.

**Comment by FFrankyy** [comment]
make_common file:
dir_guard = @mkdir -p $(@D)

CUDA_HOME := /usr/local/cuda
INTEL_ROOT := /opt/intel
MKL_ROOT = $(INTEL_ROOT)/mkl
TBB_ROOT = $(INTEL_ROOT)/tbb
USE_GPU = 1

FIND := find
CXX := g++
NVCC := $(CUDA_HOME)/bin/nvcc
NVCCFLAGS += --default-stream per-thread
CXXFLAGS += -Wall -O3 -std=c++11
LDFLAGS += -lm -L$(CUDA_HOME)/lib64 -lcudart -lcublas -lcurand -lcusparse -lmkl_rt -ltbb -lfmt
CUDA_ARCH :=    -gencode arch=compute_30,code=sm_30 \
		-gencode arch=compute_35,code=sm_35 \
		-gencode arch=compute_50,code=sm_50 \
		-gencode arch=compute_50,code=compute_50
I do not know how modify configurations in make_common file, and when I enter "make -j8" it failed:
In file include/nn/variable.h:7:24:fatal error:fmt/printf.h: no such file or directory

Could you please tell me how can I address this problem?

**Comment by Hanjun-Dai** [comment]
Could you please sync the latest version of my code and try again?

I should have removed that dependency already.

**Comment by FFrankyy** [comment]
I am sorry maybe it's the version problem, now the above problem does not occur, but a new problem comes, when I enter "make -j8", it still failed
Makefile:53:recipe for target 'build objs/cxx/nn/row_selection.o' failed
make: *** [build/objs/cxx/nn/row_selection.o] Error 1

Do you know why? Thanks!

**Comment by Hanjun-Dai** [comment]
have you tried to do `make clean` first?

**Comment by FFrankyy** [comment]
I have tried, but still failed, returned the same problem

**Comment by FFrankyy** [comment]
And I still do not know how to:
modify configurations in make_common file

**Comment by Hanjun-Dai** [comment]
could you try the single thread build:
`make`
and then give me the snapshot of the error log? Instead of the last line of log, I need something like which line triggers the error.

**Comment by FFrankyy** [comment]
when I run
make
it returned:

g++ -Wall -O3 -std=c++11 -I/usr/local/cuda/include -I/opt/intel/mkl/include -I/opt/intel/tbb/include -Iinclude -fPIC -DUSE_GPU -MMD -c -o build/objs/cxx/nn/row_selection.o src/nn/row_selection.cpp
src/nn/row_selection.cpp:3:21: fatal error: tbb/tbb.h: 没有那个文件或目录
 #include "tbb/tbb.h"
                     ^
compilation terminated.
Makefile:53: recipe for target 'build/objs/cxx/nn/row_selection.o' failed
make: *** [build/objs/cxx/nn/row_selection.o] Error 1

**Comment by Hanjun-Dai** [comment]
Thanks. Then it makes sense. 

Have you installed intel parallel studio?
If so, the default path should be `/opt/intel`.  Check and see whether you have it. 
If not, you need to first install the intel parallel studio. Students will have free license.

**Comment by FFrankyy** [comment]
Thanks, I have just installed intel parallel studio, and the previous problems seemed resolved, but when I run the mnist example and enter command:
make
it returned problems:
g++ -Wall -O3 -std=c++11 -DUSE_GPU -I/usr/local/cuda/include -I/opt/intel/mkl/include -I../../include -Iinclude -o build/mnist mnist.cpp ../../build/lib/libgnn.a -L../../build/lib -lgnn -lm  -lmkl_rt -ltbb -L/usr/local/cuda/lib64 -lcudart -lcublas -lcurand -lcusparse
/usr/bin/ld: 找不到 -lmkl_rt
/usr/bin/ld: 找不到 -ltbb
collect2: error: ld returned 1 exit status
Makefile:21: recipe for target 'build/mnist' failed
make: *** [build/mnist] Error 1

How can it be solved? Thanks!

**Comment by Hanjun-Dai** [comment]
As I mentioned in the README, please run the intel script to setup environment:
    
  in ~/.bashrc, add the following sentence
  
    source {path_to_your_intel_root/name_of_parallel_tool_box}/bin/psxevars.sh

For example:
`source /opt/intel/parallel_studio_xe_2017.4.056/bin/psxevars.sh`

Please adapt the path to your own system

**Comment by FFrankyy** [comment]
Good! Finally Got it!! Thanks!

**Comment by Hanjun-Dai** [comment]
close the issue since it is resolved.
