### ISSUE TITLE
error: ‘memcpy’ was not declared in this scope

### ISSUE THREAD

**Issue by mahdi7** [Hanjun-Dai/graphnn#19]
I am trying to build this package on my virtual machine:
- Ubuntu 16.04
- No GPU (hence no CUDA)
I have already installed Intel Parallel Studio XE 2018.

Here is the details of the error message I get:

g++ -Wall -O3 -std=c++11 -I/include -I/data/util/intel/mkl/include -I/data/util/intel/tbb/include -Iinclude -fPIC -MMD -c -o build_cpuonly/objs/cxx/nn/one_hot.o src/nn/one_hot.cpp
g++ -Wall -O3 -std=c++11 -I/include -I/data/util/intel/mkl/include -I/data/util/intel/tbb/include -Iinclude -fPIC -MMD -c -o build_cpuonly/objs/cxx/nn/variable.o src/nn/variable.cpp
g++ -Wall -O3 -std=c++11 -I/include -I/data/util/intel/mkl/include -I/data/util/intel/tbb/include -Iinclude -fPIC -MMD -c -o build_cpuonly/objs/cxx/nn/square_error.o src/nn/square_error.cpp
g++ -Wall -O3 -std=c++11 -I/include -I/data/util/intel/mkl/include -I/data/util/intel/tbb/include -Iinclude -fPIC -MMD -c -o build_cpuonly/objs/cxx/nn/is_equal.o src/nn/is_equal.cpp
src/nn/one_hot.cpp: In instantiation of ‘void gnn::OneHot<mode, Dtype>::Forward(std::vector<std::shared_ptr<gnn::Variable> >&, std::vector<std::shared_ptr<gnn::Variable> >&, gnn::Phase) [with mode = gnn::CPU; Dtype = float]’:
src/nn/one_hot.cpp:54:1:   required from here
src/nn/one_hot.cpp:43:9: error: ‘memcpy’ was not declared in this scope
   memcpy(output.data->row_ptr, idxes.data(), sizeof(int) * idxes.size());
         ^
src/nn/one_hot.cpp:44:9: error: ‘memcpy’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
   memcpy(output.data->col_idx, input.data->ptr, sizeof(int) * input.rows());
         ^
src/nn/one_hot.cpp:43:9: note: ‘memcpy’ declared here, later in the translation unit
   memcpy(output.data->row_ptr, idxes.data(), sizeof(int) * idxes.size());
         ^
src/nn/one_hot.cpp: In instantiation of ‘void gnn::OneHot<mode, Dtype>::Forward(std::vector<std::shared_ptr<gnn::Variable> >&, std::vector<std::shared_ptr<gnn::Variable> >&, gnn::Phase) [with mode = gnn::CPU; Dtype = double]’:
src/nn/one_hot.cpp:54:1:   required from here
src/nn/one_hot.cpp:43:9: error: ‘memcpy’ was not declared in this scope
src/nn/one_hot.cpp:44:9: error: ‘memcpy’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
   memcpy(output.data->col_idx, input.data->ptr, sizeof(int) * input.rows());
         ^
src/nn/one_hot.cpp:43:9: note: ‘memcpy’ declared here, later in the translation unit
   memcpy(output.data->row_ptr, idxes.data(), sizeof(int) * idxes.size());
         ^
Makefile:53: recipe for target 'build_cpuonly/objs/cxx/nn/one_hot.o' failed

**Comment by Hanjun-Dai** [comment]
Hi, I've added the cstring header, could you please check again?

**Comment by mahdi7** [comment]
I included the header <string.h> in "one_hot.cpp" and then the package was successfully built.

However, none of the examples could be built. Seems that the Makefiles are created assuming GPU_USE case. I even changed the lib_dir:=$(GNN_HOME)/build_cpuonly/lib in the Makefile, but I get this fatal error: thrust/device_vector.h: No such file

**Comment by Hanjun-Dai** [comment]
you can still install the cuda environment, even you don't have gpu.
