### ISSUE TITLE
Not able to run the mnist example

### ISSUE THREAD

**Issue by shengwa** [Hanjun-Dai/graphnn#2]
I tried to run the mnist example but there was an error:
```
./run.sh
60000 images for training
10000 images for test
testing
Assertion `isReady[VarIdx(p)]` failed in src/nn/factor_graph.cpp line 170: required variable ReduceMean_7:out_0 is not ready
```
I also found the similar error with graph classification example
```
Assertion `isReady[VarIdx(p)]` failed in src/nn/factor_graph.cpp line 170: required variable ReduceMean_21:out_0 is not ready
```

Any idea what the problem is?

**Comment by Hanjun-Dai** [comment]
Hi, are you using the latest code? I just checked the HEAD of master, and it works fine.

**Comment by shengwa** [comment]
Oh, it seems not the latest version, I'll update it and see what's going on. Thank you :)

**Comment by shengwa** [comment]
Hi, I tried the latest code but the problem was still there.
I guess I'll read more code to figure it out.

**Comment by Hanjun-Dai** [comment]
Are you using the commit 00351188349c9cfef783b5d17c2f07523891fd8e ?

**Comment by shengwa** [comment]
Yes, I'm using it.
`v1.11-85-g0035118`

**Comment by Hanjun-Dai** [comment]
Can you simply zip your code folder and send it to daihanjun@gmail.com? (excluding the data and binary files)

**Comment by Hanjun-Dai** [comment]
It seems to be the Ubuntu 16.04 issue. Feel free to reopen if the problem is still there.
