### ISSUE TITLE
src/nn/row_selection.cpp:3:21: fatal error: tbb/tbb.h: 没有那个文件或目录  #include "tbb/tbb.h"                      ^ compilation terminated. Makefile:53: recipe for target 'build/objs/cxx/nn/row_selection.o' failed

### ISSUE THREAD

**Issue by HackerHyper** [Hanjun-Dai/graphnn#20]
src/nn/row_selection.cpp:3:21: fatal error: tbb/tbb.h: 没有那个文件或目录
 #include "tbb/tbb.h"
                     ^
compilation terminated.
Makefile:53: recipe for target 'build/objs/cxx/nn/row_selection.o' failed

**Comment by Joyrocky** [comment]
> src/nn/row_selection.cpp:3:21: fatal error: tbb/tbb.h: 没有那个文件或目录
> #include "tbb/tbb.h"
> ^
> compilation terminated.
> Makefile:53: recipe for target 'build/objs/cxx/nn/row_selection.o' failed

I have the same error with you,I would like to know that how did you solve the problem?

**Comment by Hanjun-Dai** [comment]
You need to install intel TBB
