### ISSUE TITLE
thrust:system_error unknown error in docker image

### ISSUE THREAD

**Issue by tahsinkose** [Hanjun-Dai/graphnn#25]
Hi there,
I'm using Ubuntu 18.04 and planning to install an upper version of CUDA, therefore I have gone in the way to replicate the experiments of this study in a Docker image. After I have built all the workspace and executed `./run.sh` in `examples/mnist` I get `thrust:system_error unknown error`.

Have you ever received this error in a host machine or in a Docker image?

**Comment by Hanjun-Dai** [comment]
Hi,

I was working with CUDA  8.0 + Ubuntu 16.04. If you want to replicate the experiments, please try a pytorch reimplementation: https://github.com/Hanjun-Dai/pytorch_structure2vec

**Comment by tahsinkose** [comment]
Is PyTorch implementation CUDA-independent? I want to stick with Docker way, that's why I am asking.

**Comment by tahsinkose** [comment]
Anyway, I have solved the problem. It is a basic argument problem when starting the Docker container.
