### ISSUE TITLE
Error:make: *** No rule to make target 'build/kernel_mean_field', needed by 'all'.

### ISSUE THREAD

**Issue by XinxinMa11** [Hanjun-Dai/graphnn#29]
Hello,
I can run mnist successfully, but met error when i run graph_classificationas follow:
![image](https://user-images.githubusercontent.com/44078475/61574921-7733b700-aaf8-11e9-8261-7212c64f3db8.png)
Can anybody help me ? Thanks!

**Comment by Hanjun-Dai** [comment]
Hi,

If you build the graphnn in CPU mode then this Makefile won't find the library. 

I've just fixed the Makefile (remember to config the CPU/GPU mode in the Makefile first). Please pull the latest version.

**Comment by XinxinMa11** [comment]
Hi,
The code can run after update the  Makefile .
But I still meet some issues:
![image](https://user-images.githubusercontent.com/44078475/61590727-db857200-abef-11e9-9486-46c80dd0751c.png)
![image](https://user-images.githubusercontent.com/44078475/61590750-21dad100-abf0-11e9-8235-1fad772d6fcc.png)
![image](https://user-images.githubusercontent.com/44078475/61590761-50f14280-abf0-11e9-9e1e-49f06977f647.png)
![image](https://user-images.githubusercontent.com/44078475/61590764-5b134100-abf0-11e9-8aa8-8d8adb9d7b17.png)
![image](https://user-images.githubusercontent.com/44078475/61590772-6e261100-abf0-11e9-8567-78ce5344705d.png)
![image](https://user-images.githubusercontent.com/44078475/61590787-8302a480-abf0-11e9-80b1-e3d5abbdf4c0.png)
![image](https://user-images.githubusercontent.com/44078475/61590790-901f9380-abf0-11e9-95b7-e63561b54668.png)
![image](https://user-images.githubusercontent.com/44078475/61590796-9b72bf00-abf0-11e9-8372-d8d1945cc7c2.png)
![image](https://user-images.githubusercontent.com/44078475/61590800-a75e8100-abf0-11e9-994a-a004a112018f.png)
![image](https://user-images.githubusercontent.com/44078475/61590809-b7766080-abf0-11e9-9074-e1b9ba42096b.png)
![image](https://user-images.githubusercontent.com/44078475/61590813-c65d1300-abf0-11e9-8825-a9a38aa70335.png)
![image](https://user-images.githubusercontent.com/44078475/61590816-d117a800-abf0-11e9-9b1a-32570f8b55b1.png)
![image](https://user-images.githubusercontent.com/44078475/61590820-dffe5a80-abf0-11e9-8aab-a49d8cef7bd4.png)
![image](https://user-images.githubusercontent.com/44078475/61590824-ed1b4980-abf0-11e9-963a-8a6d35b74633.png)
![image](https://user-images.githubusercontent.com/44078475/61590827-f7d5de80-abf0-11e9-83f2-7b316302d612.png)
![image](https://user-images.githubusercontent.com/44078475/61590842-0623fa80-abf1-11e9-844c-7ca6604df7ff.png)
![image](https://user-images.githubusercontent.com/44078475/61590847-1340e980-abf1-11e9-9a78-8f52ada36ca7.png)
![image](https://user-images.githubusercontent.com/44078475/61590852-22279c00-abf1-11e9-847a-224625792139.png)

The error means I still use GPU mode?

**Comment by Hanjun-Dai** [comment]
make sure the 'USE_GPU' flags in Makefile and the make_common are the same.

also try to recompile gnn library, in case of any inconsistency.

**Comment by XinxinMa11** [comment]
![image](https://user-images.githubusercontent.com/44078475/61601173-dca5b600-ac66-11e9-9a5f-bc5ea4ceb632.png)
I modify the mode to 'CPU mode' and the issues fixed.
Thank you very much!!!
