### ISSUE TITLE
MKL issue

### ISSUE THREAD

**Issue by BabyCodr** [Hanjun-Dai/graphnn#33]
I have downloaded MKL and modified the make_common file to point to the directory however I am still getting a fatal error

 -o build/objs/cxx/nn/tanh.o src/nn/tanh.cpp
g++ -Wall -O3 -std=c++11 -I/usr/local/cuda/include -I/usr/parallel_studio_xe_2020/compilers_and_libraries_2020/linux/mkl/include -I/usr/parallel_studio_xe_2020/compilers_and_libraries_2020/linux/tbb/include -Iinclude -fPIC -DUSE_GPU -MMD -c -o build/objs/cxx/nn/matmul.o src/nn/matmul.cpp
In file included from src/tensor/cpu_row_sparse_tensor.cpp:5:0:
include/tensor/mkl_helper.h:4:17: fatal error: mkl.h: No such file or directory
 #include <mkl.h>
                 ^
compilation terminated.
In file included from src/tensor/cpu_dense_tensor.cpp:6:0:
include/tensor/mkl_helper.h:4:17: fatal error: mkl.h: No such file or directory
 #include <mkl.h>
                 ^
compilation terminated.
In file included from src/nn/jagged_softmax.cpp:2:0:
include/tensor/mkl_helper.h:4:17: fatal error: mkl.h: No such file or directory
 #include <mkl.h>

My make_common file is 

INTEL_ROOT := /usr/parallel_studio_xe_2020/compilers_and_libraries_2020/linux
MKL_ROOT = $(INTEL_ROOT)/mkl
TBB_ROOT = $(INTEL_ROOT)/tbb
USE_GPU = 1

**Comment by BabyCodr** [comment]
Apologies forgot to run line 

source {path_to_your_intel_root/name_of_parallel_tool_box}/bin/psxevars.sh

**Comment by cburdea** [comment]
Is there any possibility to make this code run without Parallel Toolbox? Seems like Intel replaced it (at least the free version) with oneAPI and also got rid of the psxevars.sh file, too.

**Comment by Hanjun-Dai** [comment]
sorry it was hard coded with intel MKL/TBB api.
